### ISSUE TITLE
Does not support macOS Big Sur

### ISSUE THREAD

**Issue by rsun-thoughtworks** [sprout2000/leafview#218]
![image](https://user-images.githubusercontent.com/44775081/118799626-85f47c00-b8d1-11eb-9b63-fc312da55b21.png)

**Comment by sprout2000** [comment]
Would you try LeafView-0.10.1-darwin.dmg instead of *-darwin-arm64.dmg?

**darwin.dmg (Intel):**
<img width="652" alt="x64_intel" src="https://user-images.githubusercontent.com/52094761/118897742-de656100-b945-11eb-8575-8c75f59481fd.png">

**darwin-arm64.dmg(Intel):**
<img width="652" alt="arm64_intel" src="https://user-images.githubusercontent.com/52094761/118897789-f341f480-b945-11eb-9eba-625bfd1ea74e.png">

**darwin.dmg(Apple Silicon):**
<img width="652" alt="x64_m1" src="https://user-images.githubusercontent.com/52094761/118897816-0654c480-b946-11eb-9b34-abf007c0706e.png">
