### ISSUE TITLE
Suggestion: support view images inside folder

### ISSUE THREAD

**Issue by rsun-thoughtworks** [sprout2000/leafview#219]
support view images inside folder

It is very common to view images inside a folder

**Comment by sprout2000** [comment]
@rsun-thoughtworks 
Thank you for your suggestion.

Do you mean to show thumbnails of the images in the folder?
I have tried to implement this in the past, but abandoned it because the performance degraded to an extent that could not be overlooked.
I'm sorry, but I have no intention of implementing this feature in the future.

**Comment by sprout2000** [comment]
Grid view functionality is implemented in [v2.2.0](https://github.com/sprout2000/leafview/releases/tag/v2.2.0) now.
Try it out, if you like it.
