### ISSUE TITLE
Windows Binaries (provided here)

### ISSUE THREAD

**Issue by jdev082** [sprout2000/leafview#323]
**Binaries for Windows are built and posted here (Unofficial)**

[v2.2.13](https://dl.jaydendev.repl.co/LeafView-2.2.13-win32-x64-installer.exe)

**Comment by sprout2000** [comment]
@jdev082 
Thank you for the binaries.

Since the winget releaser CI failed, I had removed the Windows binaries from the release to avoid confusion among users.
However, there seems to be a demand for it, despite the warnings that appear if you install it other than via winget, so I've uploaded the binaries for Windows again.

**Comment by jdev082** [comment]
@sprout2000 suggestion is spelled incorrectly (the issue's tag)

**Comment by sprout2000** [comment]
Oh.. it's a shame.
Thank you.
