### ISSUE TITLE
winget-releaser has been removed

### ISSUE THREAD

**Issue by vedantmgoyal2009** [sprout2000/leafview#329]
Hi, I see that winget-releaser has been removed from release `2.3.11`. I would love to know what made you remove it from the release workflow, and if I can make improvements to it to suit your needs. Thanks 🙏🏻

**Comment by sprout2000** [comment]
@vedantmgoyal2009 
Thank you for your good offer💚.
There were several cases where winget-releaser did not work well for some reason unknown to me. So I removed it temporarily at that time but it was left in place and I don't know how to restore it😵.

Windows comes with the excellent Microsoft Photo and I doubt there is any demand for a winget version of LeafView...

**Comment by vedantmgoyal2009** [comment]
Hmm, I see that you've removed Windows builds altogether. Hence, winget-releaser wouldn't be of any use here.

For Elephicon, you only support macOS. Is there any reason you are reducing supported operating systems for your projects?

**Comment by sprout2000** [comment]
@vedantmgoyal2009 
Sorry for the delay in replying as I was laid up with the flu.

> For Elephicon, you only support macOS. Is there any reason you are reducing supported operating systems for your projects?

As for Elephicon, I still continue to offer it on the Microsoft Store. This is because, unlike Winget, the Microsoft Store comes with code signing.

And I am distributing the Linux version of LeafView as a binary because I presume that Linux users could build it themselves using Node.js if they are concerned about code-signing.

**Comment by vedantmgoyal2009** [comment]
> Sorry for the delay in replying as I was laid up with the flu.

Sorry to hear that. Hope you're fine now 👍
