### ISSUE TITLE
The option to delete a photo doesn't work for me

### ISSUE THREAD

**Issue by liskaaaaaaaaaa** [sprout2000/leafview#330]
The option to delete a photo doesn't work for me.

![Przechwytywanie](https://github.com/sprout2000/leafview/assets/57771031/63f6fece-cb37-4239-bc49-867781067fc5)

2.7.0
Windows 10 1903 64 bits

**Comment by liskaaaaaaaaaa** [comment]
the option does not work when the "Do not move files to trash" option is enabled

**Comment by sprout2000** [comment]
@liskaaaaaaaaaa 
Thank you for the report.
If you have enabled the "Do not move files to trash" option in Windows, you cannot immediately delete the files due to Electron specifications.
To achieve this, you need to send a Feature Request to the [Electron project](https://github.com/electron/electron) to change the specification of [`shell.trashItem(path)`](https://www.electronjs.org/docs/latest/api/shell#shelltrashitempath).
So I cannot correct this behavior myself. I am sorry.

**Comment by liskaaaaaaaaaa** [comment]
@sprout2000
Thank you very much for your answer. 

:(
